### ISSUE TITLE
Shelly 1 Error

### ISSUE THREAD

**Issue by dvbcheck** [minamoanes/homebridge-homekit-control#6] opened 2022-12-26 12:58 UTC
/usr/local/lib/node_modules/homebridge-homekit-control/node_modules/hap-controller/lib/protocol/pairing-protocol.js:415
            throw new Error('M2: Accessory LTPK not yet set');
                  ^

Error: M2: Accessory LTPK not yet set
    at PairingProtocol.parsePairVerifyM2 (/usr/local/lib/node_modules/homebridge-homekit-control/node_modules/hap-controller/lib/protocol/pairing-protocol.js:415:19)
    at /usr/local/lib/node_modules/homebridge-homekit-control/node_modules/hap-controller/lib/transport/ip/http-client.js:237:40
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Shelly 1 HK Firmware
Version:2.11.2    Build: 20220812-225235/2.11.2-g1b146b4-master

**Comment by minamoanes** [comment] 2022-12-28 18:28
@dvbcheck thank you for opening this issue,
This is a duplicate of https://github.com/minamoanes/homebridge-homekit-control/issues/3 
Currently I'm working on a fix for it

**Comment by minamoanes** [comment] 2023-02-07 16:50
Please take a look at the comment posted on #3, and leave your feedback there: 
https://github.com/minamoanes/homebridge-homekit-control/issues/3#issuecomment-1421090670

@dvbcheck

**Closed by minamoanes** 2023-02-07 16:50 UTC
Labels: duplicate
